version: "3.8"

services:
  warde:
    image: warde_ws:humble # IMPORTANT: ensure you have built the warde image via `docker build`
    container_name: warde_ws
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/ros2_ws/src
      - ./models:/ros2_ws/models
    command: >
      bash -lc "ros2 launch warde_bt launch_all.launch.py         world:=$(ros2 pkg prefix robot_description)/models/myWorld/boxes_world.sdf         use_sim_time:=true         rviz_config_file:=$(ros2 pkg prefix robot_description)/rviz/sim.config.rviz"
